### ISSUE TITLE
Port rasa-addons to the new rasa-core version 0.11

### ISSUE THREAD

**Issue by jonDel** [mrbot-ai/rasa-addons#14]
Port rasa-addons to the new rasa-core version 0.11. Major changes broke compatibility with older versions, including dependent projects as rasa-addons. See http://rasa.com/docs/core/migrations/ for more details on how to migrate to the new version.

**Comment by znat** [comment]
Thanks @jonDel that's definitely on the list as soon as we migrate a project (or start a new one). In the meantime, if you're planning on using 0.11 with the addons, a PR would be really helpful :)
