### ISSUE TITLE
enhancement: allow rendering links in chat widget

### ISSUE THREAD

**Issue by amn41** [mrbot-ai/rasa-addons#15]
We would love to be able to show (hyper)links in the chat widget. One simple solution would be to use [remarkable](https://www.npmjs.com/package/remarkable) or similar markdown library.

@znat how would you feel about this?

**Comment by znat** [comment]
Hi @amn41 
We're planning on doing it soon. We're focusing now on making it more react embeddable, and this is next

**Comment by amn41** [comment]
awesome, glad to hear it! yeah also happy to make contributions here, just wanted to check first what you thought. 

Does it make sense for us (Rasa) to create a PR for this one?

**Comment by znat** [comment]
@amn41 what we had in mind was a simple highlight of existing links. Similar to what happens in Messenger. if you type www.something.com in a message, then it becomes a link. What you seem to suggest is the possibility to create a link with a text different from the URL it's pointing to. Correct?

**Comment by amn41** [comment]
Yes but that’s not essential. I think highlighting is sufficient :)

**Comment by znat** [comment]
@TheoTomalty : adding you to the conversation. @tmbo thanks for the suggestion I like the idea of linkifyjs
