### ISSUE TITLE
SuperAgent

### ISSUE THREAD

**Issue by PHLF** [mrbot-ai/rasa-addons#2]
No `input_validation` field in the `rules.yml` file leads to an exception:

[The superagent's message_processor](https://github.com/mrbot-ai/rasa-addons/blob/master/rasa_addons/superagent/message_processor.py#L53-L56) should be :

```python
    if self.rules.input_validation:
                error_template = self.rules.input_validation.get_error(parse_data, tracker)
                if error_template:
                    self._utter_error_and_roll_back(message, tracker, error_template)
                    return
```

**Comment by znat** [comment]
thanks @PHLF 
Fixed
