### ISSUE TITLE
How to integrate Disambiguator with RASA agent

### ISSUE THREAD

**Issue by ketansoneji** [mrbot-ai/rasa-addons#20]
Hi,

I am new to RASA. I have a need to present multiple options in case confidence scores of multiple intents are very close. The disambiguator feature form the rasa-addons library suits it well.

I was able to get the Disambiguator object with the below code:
disambiguator = Disambiguator(disamb_rule=load_yaml('./disambiguator.yaml')['disambiguation_policy'])

I do see functions as should_disambiguate, get_disambiguation_message etc.. But I need to explicitly pass the "parse_data" to it to get the output.

However, I want the bot at run time to parse the confidence scores and enforce the disambuigator rules. I think rasa addons do support that for rules.yml for validations. Not sure how to do it for Disambiguation policies.

Any inputs on how to integrate it with RASA agent or superagent would be appreciated.

Thanks.

**Comment by znat** [comment]
Hi, declarating the disambiguation policy in your rules should be enough. As soon as your intent scores satisfy the trigger you should see the disambiguation messages

**Comment by ketansoneji** [comment]
Thanks for your help.
