### ISSUE TITLE
I am getting error as "unexpected keyward"

### ISSUE THREAD

**Issue by neerajb1** [mrbot-ai/rasa-addons#22]
Hi Team , 
I am trying to figure out how to handle unexpected keyward error. Please find mine code below

Error
TypeError: load() got an unexpected keyword argument 'action_endpoint'

Code:
agent = SuperAgent.load('app/models/dialogue', interpreter=interpreter, action_endpoint=action_endpoint ,rules='rules.yml' )

**Comment by znat** [comment]
Can you share your rasa core and rasa addon versions and paste the code you're using to start the bot?

**Comment by neerajb1** [comment]
Hi Thanks for you reply. Please find all details below

RasaCore V : 0.11.11
RasaAddon  :0 4.3

Code:
def run_chat_bot(serve_forever=True):
	interpreter = RasaNLUInterpreter('app/models/nlu/default/reciprocienlu')
	action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")
       agent = SuperAgent.load('app/models/dialogue', interpreter=interpreter ,action_endpoint=action_endpoint,rules_file='rules.yml')
	rasa_core.run.serve_application(agent ,channel='cmdline')
	return agent


Error:
TypeError: load() got an unexpected keyword argument 'action_endpoint'

**Comment by znat** [comment]
0.4.x is not compatible with core 0.11.x
Please use 0.5.x
